name: flutter_uix
description: A minimal version of VelocityX framework.
# author: Fluttensor
version: 0.1.2-nullsafety.2
repository: https://github.com/Mj23978/mafia_comentator


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
